package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.commitStatusPublisher
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'A'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("A")) {
    params {
        add {
            param("teamcity.commitStatusPublisher.githubContext", "Verify Pull Request")
        }
    }

    features {
        add {
            commitStatusPublisher {
                publisher = github {
                    githubUrl = "https://api.github.com"
                    authType = personalToken {
                        token = "credentialsJSON:4c1d31a3-a138-4693-9035-4a8653fda258"
                    }
                }
            }
        }
    }
}
