package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.PullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.pullRequests
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'subProj_bt_0_105'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("subProj_bt_0_105")) {
    features {
        val feature1 = find<PullRequests> {
            pullRequests {
                vcsRootExtId = "Manyconfigs_HttpsGithubComGradleGradleGit"
                provider = github {
                    authType = token {
                        token = "credentialsJSON:710498e1-c878-4b58-b5f1-cee3a258db6f"
                    }
                    filterAuthorRole = PullRequests.GitHubRoleFilter.MEMBER
                }
            }
        }
        feature1.apply {
            provider = github {
                serverUrl = ""
                authType = token {
                    token = "credentialsJSON:710498e1-c878-4b58-b5f1-cee3a258db6f"
                }
                filterSourceBranch = ""
                filterTargetBranch = ""
                filterAuthorRole = PullRequests.GitHubRoleFilter.EVERYBODY
            }
        }
    }
}
