package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.vcs
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'subProj_bt_0_15'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("subProj_bt_0_15")) {
    triggers {
        add {
            vcs {
            }
        }
    }
}
