package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the vcsRoot with id = 'HttpsGithubComGradleGradleGit'
accordingly, and delete the patch script.
*/
changeVcsRoot(RelativeId("HttpsGithubComGradleGradleGit")) {
    val expected = GitVcsRoot({
        id("HttpsGithubComGradleGradleGit")
        name = "https://github.com/gradle/gradle.git"
        url = "https://github.com/gradle/gradle.git"
        branch = "refs/heads/master"
    })

    check(this == expected) {
        "Unexpected VCS root settings"
    }

    (this as GitVcsRoot).apply {
        branchSpec = "refs/heads/(*)"
    }

}
