package patches.vcsRoots

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*
import jetbrains.buildServer.configs.kotlin.v2019_2.vcs.GitVcsRoot

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a vcsRoot with id = 'subProj_1_HttpsGithubComGradleGradleGit'
in the project with id = 'subProj_1', and delete the patch script.
*/
create(RelativeId("subProj_1"), GitVcsRoot({
    id("subProj_1_HttpsGithubComGradleGradleGit")
    name = "https://github.com/gradle/gradle.git"
    url = "https://github.com/gradle/gradle.git"
    branch = "refs/heads/master"
    branchSpec = "refs/heads/(*)"
}))

